# Generated by Django 3.2.9 on 2022-02-03 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Counsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr.', 'Mr.'), ('mrs.', 'Mrs.'), ('dr.', 'Dr.'), ('prof.', 'Prof.')], db_index=True, default='Mr.', max_length=20)),
                ('firstName', models.CharField(blank=True, db_index=True, default=None, max_length=255)),
                ('lastName', models.CharField(blank=True, db_index=True, default=None, max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, default='Male', max_length=25)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('contact', models.IntegerField(default=None)),
                ('profile', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
                ('about', models.TextField(blank=True, default=None)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('person_id', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('pin', models.IntegerField(blank=True, db_index=True, default=None, null=True)),
                ('option', models.CharField(blank=True, choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('student', 'Student'), ('staff', 'Staff')], default=None, max_length=255, null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SuperCounsellor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(choices=[('mr.', 'Mr.'), ('mrs.', 'Mrs.'), ('dr.', 'Dr.'), ('prof.', 'Prof.')], db_index=True, default='Mr.', max_length=20)),
                ('firstName', models.CharField(blank=True, db_index=True, default=None, max_length=255)),
                ('lastName', models.CharField(blank=True, db_index=True, default=None, max_length=255)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], db_index=True, default='Male', max_length=25)),
                ('email', models.EmailField(blank=True, default=None, max_length=254)),
                ('contact', models.IntegerField(default=None)),
                ('profile', models.ImageField(blank=True, default=None, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name_plural': 'Super Counsellors',
            },
        ),
        migrations.CreateModel(
            name='Therapy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('therapies_offered', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('counsellor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='therapy', to='counsellingApp.counsellor')),
            ],
            options={
                'verbose_name_plural': 'therapies',
            },
        ),
        migrations.CreateModel(
            name='Specialities',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_specialities', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('counsellor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='specialities', to='counsellingApp.counsellor')),
            ],
            options={
                'verbose_name_plural': 'specialities',
            },
        ),
        migrations.CreateModel(
            name='Experience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experience_institution', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('experience_position', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('counsellor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='experience', to='counsellingApp.counsellor')),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('education_institution', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('year_completed', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('counsellor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='education', to='counsellingApp.counsellor')),
            ],
            options={
                'verbose_name_plural': 'education',
            },
        ),
        migrations.CreateModel(
            name='Availability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField(blank=True, default=None, null=True)),
                ('end_time', models.TimeField(blank=True, default=None, null=True)),
                ('date', models.CharField(blank=True, choices=[('monday', 'Monday'), ('tuesday', 'Tuesday'), ('wednesday', 'Wednesday'), ('thursday', 'Thursday'), ('friday', 'Friday')], default=None, max_length=255, null=True)),
                ('counsellor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='availability', to='counsellingApp.counsellor')),
            ],
            options={
                'verbose_name_plural': 'availabilities',
            },
        ),
        migrations.CreateModel(
            name='Achievement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awards', models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True)),
                ('counsellor', models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='achievement', to='counsellingApp.counsellor')),
            ],
        ),
    ]
