# Generated by Django 3.2.9 on 2022-02-11 01:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], db_index=True, default='Mr.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], db_index=True, default='Mr.', max_length=20, null=True),
        ),
    ]
