# Generated by Django 4.0.3 on 2022-06-07 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='endtime',
            field=models.TextField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='startime',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
