# Generated by Django 3.2.9 on 2022-03-01 00:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='user_id',
            field=models.IntegerField(blank=True, default=uuid.uuid4, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='user_id',
            field=models.IntegerField(blank=True, default=uuid.uuid4, null=True),
        ),
    ]
