# Generated by Django 3.2.9 on 2022-02-04 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='pin',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='supercounsellor',
            name='pin',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
