# Generated by Django 3.2.9 on 2022-02-15 14:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0002_bookings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bookings',
            options={'verbose_name_plural': 'Bookings'},
        ),
        migrations.AddField(
            model_name='bookings',
            name='counsellor',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='counsellingApp.counsellor'),
        ),
    ]
