# Generated by Django 3.2.9 on 2022-02-04 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0002_auto_20220204_1158'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('student', 'Student'), ('staff', 'Staff')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='counsellor',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='supercounsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('student', 'Student'), ('staff', 'Staff')], default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supercounsellor',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
