# Generated by Django 4.0.3 on 2022-06-07 13:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0002_alter_availability_endtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='availability',
            old_name='not_availiable',
            new_name='availiable',
        ),
    ]
