# Generated by Django 3.2.9 on 2022-03-01 00:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0003_auto_20220301_0052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('student', 'Student')], default='Counsellor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('student', 'Student')], default='Counsellor', max_length=255, null=True),
        ),
    ]
