# Generated by Django 3.2.9 on 2022-02-06 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0003_auto_20220204_1207'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='pin',
            new_name='pin_log',
        ),
    ]
