# Generated by Django 3.2.9 on 2022-03-14 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0003_students_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='text',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
