# Generated by Django 4.0.5 on 2022-06-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0003_rename_not_availiable_availability_availiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='age',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='students',
            name='contact',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
