# Generated by Django 4.0.5 on 2022-06-13 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0004_alter_students_age_alter_students_contact'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='availiable',
        ),
        migrations.AddField(
            model_name='availability',
            name='availabletime',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
