# Generated by Django 3.2.9 on 2022-03-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0004_alter_notifications_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='subject',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
    ]
