# Generated by Django 3.2.9 on 2022-02-07 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0004_rename_pin_login_pin_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='counsellor',
            name='occupation',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='supercounsellor',
            name='occupation',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
