# Generated by Django 3.2.9 on 2022-02-16 02:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0004_meetings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookings',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='bookings',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='meetings',
            name='start_time',
        ),
        migrations.AlterField(
            model_name='availability',
            name='date',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bookings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='meetings',
            name='date',
            field=models.DateTimeField(auto_now_add=True, max_length=255, null=True),
        ),
    ]
