# Generated by Django 3.2.9 on 2022-02-16 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0005_auto_20220216_0240'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='counsellor_user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
