# Generated by Django 4.0.5 on 2022-06-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0005_remove_availability_availiable_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='time',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
