# Generated by Django 3.2.9 on 2022-02-16 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0006_bookings_counsellor_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='student_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved')], db_index=True, default='Pending', max_length=255, null=True),
        ),
    ]
