# Generated by Django 3.2.9 on 2022-02-08 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0006_auto_20220208_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='title',
            field=models.CharField(choices=[('mr.', 'Mr.'), ('mrs.', 'Mrs.'), ('dr.', 'Dr.'), ('prof.', 'Prof.')], db_index=True, default='Mr.', max_length=20),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='title',
            field=models.CharField(choices=[('mr.', 'Mr.'), ('mrs.', 'Mrs.'), ('dr.', 'Dr.'), ('prof.', 'Prof.')], db_index=True, default='Mr.', max_length=20),
        ),
    ]
