# Generated by Django 3.2.9 on 2022-03-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0006_auto_20220314_1353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notifications',
            name='counsellor_firstName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='counsellor_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='counsellor_lastName',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='counsellor_title',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='notifications',
            name='student_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
