# Generated by Django 4.0.5 on 2022-06-13 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0006_bookings_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookings',
            name='day',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
