# Generated by Django 3.2.9 on 2022-03-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0007_auto_20220314_1407'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='counsellor_profile',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='images/'),
        ),
    ]
