# Generated by Django 3.2.9 on 2022-03-11 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0007_auto_20220301_1304'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('STUDENT', 'Student')], default='counsellor', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='option',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('STUDENT', 'Student')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('STUDENT', 'Student')], default='counsellor', max_length=255, null=True),
        ),
    ]
