# Generated by Django 3.2.9 on 2022-02-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0008_auto_20220208_1203'),
    ]

    operations = [
        migrations.RenameField(
            model_name='login',
            old_name='person',
            new_name='person_firstname',
        ),
        migrations.AddField(
            model_name='login',
            name='person_lastname',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
