# Generated by Django 3.2.9 on 2022-03-15 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0008_notifications_counsellor_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
