# Generated by Django 3.2.9 on 2022-02-09 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0009_auto_20220208_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='achievement',
            name='user_id',
            field=models.CharField(blank=True, db_index=True, default=None, max_length=255, null=True),
        ),
    ]
