# Generated by Django 3.2.9 on 2022-03-11 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0009_notifications'),
    ]

    operations = [
        migrations.AddField(
            model_name='notifications',
            name='counsellor_firstName',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='notifications',
            name='counsellor_lastName',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AddField(
            model_name='notifications',
            name='counsellor_title',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
