# Generated by Django 3.2.9 on 2022-03-15 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0009_notifications_date_time'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'ordering': ['-date_time'], 'verbose_name_plural': 'Notifications'},
        ),
    ]
