# Generated by Django 3.2.9 on 2022-02-28 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0010_rename_date_availability_day'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='day',
            field=models.DateField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
