# Generated by Django 3.2.9 on 2022-03-12 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0010_auto_20220311_1555'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='notifications',
            options={'verbose_name_plural': 'Notifications'},
        ),
    ]
