# Generated by Django 3.2.9 on 2022-02-28 01:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0011_alter_availability_day'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Availability',
            new_name='Event',
        ),
    ]
