# Generated by Django 3.2.9 on 2022-02-28 01:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0012_rename_availability_event'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event',
            new_name='Availability',
        ),
    ]
