# Generated by Django 3.2.9 on 2022-03-12 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0012_students'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('STUDENT', 'Student')], default='COUNSELLOR', max_length=255),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('STUDENT', 'Student')], default='COUNSELLOR', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('STUDENT', 'Student')], default='COUNSELLOR', max_length=255, null=True),
        ),
    ]
