# Generated by Django 3.2.9 on 2022-02-28 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0013_rename_event_availability'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.Dr', 'Rev.Dr'), ('Dr.Mrs', 'Dr.Mrs'), ('Rev.Fr', 'Rev.Fr'), ('Rev.Fr.Dr', 'Rev.Fr.Dr')], db_index=True, default=None, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.'), ('Rev.Dr', 'Rev.Dr'), ('Dr.Mrs', 'Dr.Mrs'), ('Rev.Fr', 'Rev.Fr'), ('Rev.Fr.Dr', 'Rev.Fr.Dr')], db_index=True, default=None, max_length=20, null=True),
        ),
    ]
