# Generated by Django 3.2.9 on 2022-03-12 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0013_auto_20220312_2249'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookings',
            name='counsellor',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
