# Generated by Django 3.2.9 on 2022-02-09 15:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0013_auto_20220209_1518'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='user_id',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
