# Generated by Django 4.0.3 on 2022-03-25 19:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0014_dreamreal'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Dreamreal',
        ),
    ]
