# Generated by Django 3.2.9 on 2022-03-12 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0014_alter_bookings_counsellor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='profile',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
