# Generated by Django 4.0.3 on 2022-03-25 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0015_delete_dreamreal'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='availability',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='availability',
            name='start_time',
        ),
    ]
