# Generated by Django 3.2.9 on 2022-02-10 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0015_auto_20220210_0015'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='contact',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='contact',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
