# Generated by Django 3.2.9 on 2022-03-12 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0015_alter_students_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='students',
            name='status',
            field=models.CharField(choices=[('ADMIN', 'Admin'), ('COUNSELLOR', 'Counsellor'), ('STUDENT', 'Student')], default='STUDENT', max_length=255),
        ),
    ]
