# Generated by Django 3.2.9 on 2022-02-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0016_auto_20220228_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('student', 'Student')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='login',
            name='option',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('student', 'Student')], default=None, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='status',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('counsellor', 'Counsellor'), ('student', 'Student')], default=None, max_length=255, null=True),
        ),
    ]
