# Generated by Django 4.0.3 on 2022-03-25 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0016_remove_availability_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='hours',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='minutes',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='slots',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
