# Generated by Django 3.2.9 on 2022-02-10 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0016_auto_20220210_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], db_index=True, default='Male', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='counsellor',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], db_index=True, default='Mr.', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='email',
            field=models.EmailField(blank=True, default=None, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='gender',
            field=models.CharField(blank=True, choices=[('male', 'Male'), ('female', 'Female')], db_index=True, default='Male', max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='supercounsellor',
            name='title',
            field=models.CharField(blank=True, choices=[('Mr.', 'Mr.'), ('Mrs.', 'Mrs.'), ('Dr.', 'Dr.'), ('Prof.', 'Prof.')], db_index=True, default='Mr.', max_length=20, null=True),
        ),
    ]
