# Generated by Django 3.2.9 on 2022-03-12 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0016_alter_students_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='students',
            name='pin',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
