# Generated by Django 3.2.9 on 2022-02-10 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0018_auto_20220210_1351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='counsellor',
            name='about',
            field=models.TextField(blank=True, default=None, null=True),
        ),
    ]
