# Generated by Django 4.0.3 on 2022-03-29 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0019_alter_availability_slots'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='hours',
            field=models.IntegerField(blank=True, choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default=None, null=True),
        ),
    ]
