# Generated by Django 4.0.3 on 2022-03-29 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0022_alter_availability_hours'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='minutes',
            field=models.IntegerField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55')], default=None, null=True),
        ),
    ]
