# Generated by Django 3.2.9 on 2022-04-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0025_alter_availability_hours_alter_availability_minutes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='endtime',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='availability',
            name='startime',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
