# Generated by Django 3.2.9 on 2022-04-18 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0026_auto_20220418_1159'),
    ]

    operations = [
        migrations.AddField(
            model_name='availability',
            name='not_availiable',
            field=models.BooleanField(blank=True, default=None, null=True),
        ),
    ]
