# Generated by Django 3.2.9 on 2022-04-18 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counsellingApp', '0027_availability_not_availiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availability',
            name='hours',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='minutes',
            field=models.CharField(blank=True, choices=[('0', '0'), ('5', '5'), ('10', '10'), ('15', '15'), ('20', '20'), ('25', '25'), ('30', '30'), ('35', '35'), ('40', '40'), ('45', '45'), ('50', '50'), ('55', '55')], default='0', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='availability',
            name='slots',
            field=models.CharField(blank=True, choices=[('0', '0'), ('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9')], default='0', max_length=255, null=True),
        ),
    ]
